

# TODO: assign fixed IP addresses

version: '3'

# for organization, see https://nickjanetakis.com/blog/docker-tip-10-project-structure-with-multiple-dockerfiles-and-docker-compose

services:
    sshd:
        container_name: sshd
        build: ./sshd
        networks:
            testing_net:
                ipv4_address: 172.28.1.2


# https://www.nginx.com/blog/running-non-ssl-protocols-over-ssl-port-nginx-1-15-2/
# https://unix.stackexchange.com/questions/290223/how-to-configure-nginx-as-a-reverse-proxy-for-different-port-numbers

    nginx:
        container_name: nginx
        image: "nginx:stable"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 22:22
            - 80:80
            - 443:443
        networks:
            testing_net:
                ipv4_address: 172.28.1.3


# https://hub.docker.com/_/nginx?tab=description
# docker run --name some-nginx -v /some/content:/usr/share/nginx/html:ro -d nginx

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
