



version: '3.8'

services:
 

    node_1:
        container_name: server
        #image: wg
        build: .
        volumes:
        - ./temp:/etc/wireguard
        tty: true
        stdin_open: true
        cap_add:
            - ALL
        networks:
            testing_net:
                ipv4_address: 172.29.1.2


    node_2:
        container_name: client
        #image: wg
        build: .
        volumes:
        - ./temp:/etc/wireguard
        tty: true
        stdin_open: true
        cap_add:
            - ALL
        # user: nobody
        networks:
            testing_net:
                ipv4_address: 172.29.1.3


networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.29.1.0/24
